In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
c = np.array( [[20,30,40,50]] )

In [3]:
a.resize(2,2)

In [4]:
a[np.nonzero(a[:, 0] == 20)]

array([[20, 30]])

In [7]:
a[:, 1] = 60

In [11]:
a

array([[20, 60],
       [40, 60]])

In [10]:
np.mean(a, axis = 0)

array([ 30.,  60.])

In [58]:
a = np.mat(a)

array([0, 1, 2, 3])

In [61]:
np.mean(a, axis = 0)[0]

matrix([[ 30.,  40.]])

In [36]:
c.shape

(1, 4)

In [37]:
d = c[0, :]

In [38]:
d.shape

(4,)

In [39]:
e = c[:, 0]

In [40]:
e.shape

(1,)

In [47]:
f = c.transpose()

In [48]:
f.shape

(4, 1)

In [49]:
g = a.transpose()

In [50]:
g.shape

(4,)

In [28]:
a.reshape(2,2)

array([[20, 30],
       [40, 50]])

In [30]:
a.resize((2,2))

In [32]:
a

array([[20, 30],
       [40, 50]])

In [24]:
c = b.dtype

In [26]:
np.max(a)

50

In [23]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

In [9]:
np.arange?