In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
 m = np.matrix('[1, 2; 3, 4]')

In [5]:
m.I

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [6]:
m

matrix([[1, 2],
        [3, 4]])

In [7]:
m.getI()

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [8]:
m

matrix([[1, 2],
        [3, 4]])