In [1]:
# import
import numpy as np

In [58]:
a = np.floor(10 * np.random.random((3,4)))

In [74]:
a

array([[ 1.,  2.,  2.,  6.,  0.,  4.],
       [ 7.,  3.,  3.,  3.,  8.,  9.]])

In [72]:
a.reshape((2,6))

array([[ 1.,  2.,  2.,  6.,  0.,  4.],
       [ 7.,  3.,  3.,  3.,  8.,  9.]])

In [73]:
a.resize((2,6))

In [60]:
np.floor(a)

array([[ 1.,  2.,  2.,  6.],
       [ 0.,  4.,  7.,  3.],
       [ 3.,  3.,  8.,  9.]])

In [49]:
a += b

In [50]:
a

array([[5, 3],
       [3, 7]])