In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [54]:
def loadExData():
    return[[0, 0, 0, 2, 2],
           [0, 0, 0, 3, 3],
           [0, 0, 0, 1, 1],
           [1, 1, 1, 0, 0],
           [2, 2, 2, 0, 0],
           [5, 5, 5, 0, 0],
           [1, 1, 1, 0, 0]]

In [55]:
dataArr = np.array(loadExData())
U, Sigma, VT = np.linalg.svd(dataArr)

In [57]:
def loadExData2():
    return[[0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5],
           [0, 0, 0, 3, 0, 4, 0, 0, 0, 0, 3],
           [0, 0, 0, 0, 4, 0, 0, 1, 0, 4, 0],
           [3, 3, 4, 0, 0, 0, 0, 2, 2, 0, 0],
           [5, 4, 5, 0, 0, 0, 0, 5, 5, 0, 0],
           [0, 0, 0, 0, 5, 0, 1, 0, 0, 5, 0],
           [4, 3, 4, 0, 0, 0, 0, 5, 5, 0, 1],
           [0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 4],
           [0, 0, 0, 2, 0, 2, 5, 0, 0, 1, 2],
           [0, 0, 0, 0, 5, 0, 0, 0, 0, 4, 0],
           [1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0]]

In [ ]:
def eulidSim(inA, inB):
    return 1.0 / (1.0 + la.norm(inA - inB))

def pearsSim(inA, inB):
    if len(inA) < 3:
        return 1.0
    return 0.5 + 0.5 * np.corrcoef(inA, inB, rowvar = 0)[0][1]

def cosSim(inA, inB):
    num = float(np.dot(inA, inB.T))
    denom = la.norm(inA) * la.norm(inB)
    return 0.5 + 0.5 * (num / denom)

def standEst(dataMat, user, simMeas, item):
    m, n = dataMat.shape
    simTotal = 0.0
    ratSimTotal = 0.0
    for j in range(n):
        userRating = dataMat[user, j]
        if userRating == 0:
            continue
        overlap = np.nonzero( np.logical_and(dataMat[:, item] > 0, dataMat[:, j] > 0) )[0]
        if len(overlap) == 0:
            similarity = 0
        else:
            similarity = simMeas(dataMat[overlap, item], dataMat[overlap, j])
        simTotal += similarity
        ratSimTotal += similarity * userRating
    if simTotal == 0:
        return 0
    else:
        return ratSimTotal / simTotal
    
def recommend(dataMat, user, N=3, simMeas=cosSim, estMethod=standEst):
    unratedItems = np.nonzero(dataMat[user, :] == 0)[0]
    if len(unratedItems) == 0:
        return 'you rated everything'
    itemScores = []
    for item in unratedItems:
        estimatedScore = estMethod(dataMat, user, simMeas, item)
        itemScores.append((item, estimatedScore))
    return sorted(itemScores, key = lambda jj:jj[1], reverse=True)[:N]

In [59]:
mymat = np.array(loadExData())
mymat[0, 1] = mymat[0, 0] = mymat[1, 0] = mymat[2, 0] = 4
mymat[3, 3] = 2  # 行表示用户，列表示物品

In [61]:
mymat

array([[4, 4, 0, 2, 2],
       [4, 0, 0, 3, 3],
       [4, 0, 0, 1, 1],
       [1, 1, 1, 2, 0],
       [2, 2, 2, 0, 0],
       [5, 5, 5, 0, 0],
       [1, 1, 1, 0, 0]])

In [84]:
mymat[overlap, 1]

array([4, 1, 2, 5, 1])

In [81]:
np.mat(mymat)[3,3]

2

In [77]:
mymat[:, 1] > 0

array([ True, False, False,  True,  True,  True,  True], dtype=bool)

In [78]:
mymat[:, 0] > 0

array([ True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [83]:
overlap = np.nonzero(np.logical_and(mymat[:, 1] > 0, mymat[:, 0] > 0))[0]

In [65]:
np.nonzero(mymat[2, :] == 0)

(array([1, 2]),)

In [66]:
np.nonzero(np.mat(mymat)[2, :] == 0)

(array([0, 0]), array([1, 2]))

In [71]:
### ndarray对象仅取一行或者一列会导致降维，不在被视为一个二维矩阵
print mymat[2, :].shape
print mymat[:, 2].shape
print np.mat(mymat)[2,:].shape
print np.mat(mymat)[:,2].shape

(5,)
(7,)
(1, 5)
(7, 1)
