In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [97]:
a=np.array([1,-3,3,3,-5,3,6,-6,4], dtype = 'float64').reshape(3,3)

In [98]:
a.dtype

dtype('float64')

In [99]:
a[1,1] = np.nan

In [104]:
np.nonzero(~np.isnan(a[:, 1]))[0]

array([0, 2])

In [105]:
a[ np.nonzero(~np.isnan(a[:, 1]))[0] , :]

array([[ 1., -3.,  3.],
       [ 6., -6.,  4.]])

In [108]:
a[ ~ np.isnan(a[:, 1]), 1]

array([-3., -6.])

In [93]:
np.mean(a[1:3,1])

-5.5

In [42]:
np.argsort(a)

array([7, 4, 1, 0, 2, 3, 5, 8, 6])

In [23]:
a=np.array([[1,2,3],[4,5,9]])

In [12]:
np.dot(a, a.T)

array([[14, 32],
       [32, 77]])

In [13]:
np.mat(a) * np.mat(a.T)

matrix([[14, 32],
        [32, 77]])

In [25]:
np.cov(a.T, rowvar = 0)# rowvar 为false，表示将每一行看做一个样本

array([[ 1. ,  2.5],
       [ 2.5,  7. ]])

In [24]:
np.cov(a) # 默认将a的每一列表示一个观察值，即一个样本，每一行表示一个特征

array([[ 1. ,  2.5],
       [ 2.5,  7. ]])

In [26]:
np.diag((1,2,3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [68]:
a=np.array([0,1,1,1,0,1,1,1,0]).reshape(3,3)

In [69]:
a

array([[0, 1, 1],
       [1, 0, 1],
       [1, 1, 0]])

In [70]:
w,v = np.linalg.eig(a)

In [71]:
w

array([-1.,  2., -1.])

In [72]:
v

array([[-0.81649658,  0.57735027,  0.22645541],
       [ 0.40824829,  0.57735027, -0.79259392],
       [ 0.40824829,  0.57735027,  0.56613852]])

In [78]:
np.dot(np.array([v[:,0]]), np.array([v[:,0]]).T)

array([[ 1.]])

In [75]:
np.mat(v) * np.mat(np.diag(w)) * (np.mat(v).I)

matrix([[ -2.40548322e-16,   1.00000000e+00,   1.00000000e+00],
        [  1.00000000e+00,  -1.11022302e-16,   1.00000000e+00],
        [  1.00000000e+00,   1.00000000e+00,  -1.11022302e-16]])

In [37]:
b=np.mat(a)
w,v = np.linalg.eig(b)

In [40]:
w.shape

(3,)

In [39]:
v

matrix([[-0.40824829+0.j        ,  0.24400118-0.40702229j,
          0.24400118+0.40702229j],
        [-0.40824829+0.j        , -0.41621909-0.40702229j,
         -0.41621909+0.40702229j],
        [-0.81649658+0.j        , -0.66022027+0.j        , -0.66022027-0.j        ]])

In [90]:
~np.isnan(np.log(-1))

d:\python27\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in log
  if __name__ == '__main__':


False